-- Graveyard: the two tables the site needs, and the policies that keep them safe.
--
-- Run this once in the Supabase SQL editor. It is idempotent: running it twice
-- changes nothing.
--
-- THE THREAT MODEL, because it decides every policy below. The key the site
-- ships with is the PUBLISHABLE key. It is meant to be public and it is in the
-- page source, so anyone who opens the site has it. Row level security is
-- therefore not a nicety here: without it, any visitor can read, rewrite and
-- delete every row in these tables with one line of javascript. Every table
-- below has RLS on and grants exactly two rights to the public: read, and
-- append. Nothing anonymous may ever update or delete.

-- --------------------------------------------------------------------------
-- LEVELS: the graveyards people build in the editor.
-- --------------------------------------------------------------------------
create table if not exists public.levels (
  id          uuid primary key default gen_random_uuid(),
  -- The short code that goes in a URL. Generated by the client, checked here.
  slug        text not null unique
              check (slug ~ '^[a-z0-9]{6,16}$'),
  name        text not null
              check (char_length(name) between 1 and 60),
  author      text check (author is null or char_length(author) <= 40),
  -- The level document itself, exactly what the editor's save button writes.
  doc         jsonb not null
              -- A 30 by 30 level with a few dozen props is tens of kilobytes.
              -- 512 KB is generous and still stops someone using the table as
              -- free file hosting.
              check (pg_column_size(doc) < 524288),
  created_at  timestamptz not null default now()
);

create index if not exists levels_created_at_idx on public.levels (created_at desc);

alter table public.levels enable row level security;

drop policy if exists "levels are public" on public.levels;
create policy "levels are public"
  on public.levels for select
  using (true);

drop policy if exists "anyone may publish a level" on public.levels;
create policy "anyone may publish a level"
  on public.levels for insert
  with check (true);

-- --------------------------------------------------------------------------
-- SCORES: the leaderboard.
-- --------------------------------------------------------------------------
create table if not exists public.scores (
  id          uuid primary key default gen_random_uuid(),
  name        text not null
              check (char_length(name) between 1 and 20),
  score       integer not null check (score >= 0 and score <= 1000000),
  fireflies   integer not null check (fireflies >= 0 and fireflies <= 100000),
  -- How long the run lasted, in seconds. Kept because it is the cheapest
  -- plausibility signal there is: a huge score in a few seconds is a lie.
  seconds     integer not null check (seconds >= 0 and seconds <= 86400),
  -- Which level it was set on, if it was a published one.
  level_slug  text references public.levels (slug) on delete set null,
  created_at  timestamptz not null default now(),

  -- A run cannot collect more than a few fireflies a second however good the
  -- player is. This does not make the board honest, see the note below, but it
  -- does reject the laziest forgeries for free.
  check (fireflies <= 5 + seconds * 3)
);

create index if not exists scores_board_idx on public.scores (score desc, created_at asc);
create index if not exists scores_level_idx on public.scores (level_slug, score desc);

alter table public.scores enable row level security;

drop policy if exists "scores are public" on public.scores;
create policy "scores are public"
  on public.scores for select
  using (true);

drop policy if exists "anyone may post a score" on public.scores;
create policy "anyone may post a score"
  on public.scores for insert
  with check (true);

-- --------------------------------------------------------------------------
-- HONESTY, and it is worth reading before trusting the board.
--
-- Anyone holding the publishable key can post any score that satisfies the
-- constraints above, without playing. That is not a flaw in this schema, it is
-- what an anonymous client-written leaderboard IS. The constraints reject
-- nonsense, not cheating.
--
-- Making it actually trustworthy needs the score to be written by something the
-- player does not control: an edge function that the client sends the run's
-- inputs to, which replays them against the same deterministic rules the game
-- uses and writes the score itself. The game's rules already run headless with
-- no renderer, which is most of the work, and its levels are seeded and
-- deterministic. Worth doing the day the board matters. Not worth doing before.
-- --------------------------------------------------------------------------
